'use strict'; 
var zon_config = {
"CONFIG_MAKEFLAGS": "DIST=APP RELEASE=y AUTO_SIGN=y CONFIG_BATREQ=y CONFIG_BAT_CYCLE=y CONFIG_BAT_PLATFORM=app_win64r",
"CONFIG_LUM": false,
"ARCH_CPU": "X86",
"BUILDTYPE_DEBUG": false,
"_RELEASE": true,
"_RELEASE_LEVEL": 2,
"CONFIG_BUILD_DATE": "02-Jul-19 18:00:13",
"ZON_VERSION": "1.142.572",
"ZON_VERSION_1": 1,
"ZON_VERSION_2": 142,
"ZON_VERSION_3": 572,
"ZON_COPYRIGHT_YEAR": "2019",
"SVC_EXE": "hola_svc.exe",
"SVC_EXE_ANDROID": "libhola_svc.so",
"UPDATER_EXE": "hola_updater.exe",
"PLUGIN_EXE": "hola_plugin.exe",
"PLUGIN_EXE_X64": "hola_plugin_x64.exe",
"NET_SVC_EXE": "net_svc.exe",
"NET_SVC_ZIP": "net_svc-x64-1.142.572.zip",
"NET_SVC_ZIP_PDB": "net_svc-x64-1.142.572-pdb.zip",
"BEXT_CHROME_DLL_ID_REL": "pdehmppfilefbolgganhfihpbmjlgebh",
"BEXT_CHROME_ID_REL": "pnknnijoleibcpmkdcooclmnjmmdhgbg",
"BEXT_CHROME_CWS_ID_REL": "gkojfkhlekighikafcpjkiklfbnlmeio",
"BEXT_CHROME_CWS_PLUGIN_ID": "mhcmfkkjmkcfgelgdpndepmimbmkbpfp",
"BEXT_OPERA_ADDONS_ID_REL": "ekmmelpnmfdegjhnmadddcfjcahpajnm",
"BEXT_FF_ID_REL_SIGNED": "ff_ext@hola.org",
"BEXT_FF_ORIGIN_SIGNED": "resource://ff_ext-at-hola-dot-org",
"BEXT_FF_ID_REL": "jid1-4P0kohSJxU1qGg@jetpack",
"BEXT_FF_ORIGIN": "resource://jid1-4p0kohsjxu1qgg-at-jetpack",
"CONFIG_MP_CHROME": false,
"CONFIG_MP_OPERA": true,
"BEXT_PLUGIN": false,
"BEXT": 1,
"BEXT_VA_CHROME_ID_REL": "chgpmaaockmdehmidghebcjafhihlgha",
"BEXT_LUM_CHROME_WWW_ID": "bgnknkfnajhbeohlmmkopjlokfebbpac",
"HOLA_ADBLOCK_ID_REL": "lalfpjdbhpmnhfofkckdpkljeilmogfl"
};
if (typeof module=='object'&&module&&module.exports)
    module.exports = zon_config;else if (typeof define=='function') define(zon_config);
