'use strict';var vca={TAB:0,Bk:1,yo:2},px=function(){return new sb("MediaRouter.CastStreaming.Session.Launch")},qx=function(){return new yb("MediaRouter.CastStreaming.Session.Length")},rx=function(a){Cb("MediaRouter.CastStreaming.Start.Success",a,vca)};var sx=hb("mr.mirror.cast.LogUploader"),ux=function(a,c,b){tx("raw_events.log.gz",a,c,b);return c?"https://crash.corp.google.com/samples?reportid=&q="+encodeURIComponent("UserComments='"+c+"'"):""},tx=function(a,c,b,d){if(0==c.size)sx.info("Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,c);b&&e.append("comments",b);Wv("https://clients2.google.com/cr/report",function(f){f=f.target;
var g=null;dw(f)?(g=ew(f),sx.info("Upload to Crash succeeded: "+g)):sx.info("Upload to Crash failed. HTTP status: "+f.Wa());d&&d(g)},"POST",e,void 0,3E4)}};var vx=function(){this.b=0;cm(this)},xx=function(){wx||(wx=new vx);return wx},wca=function(){var a=xx(),c={fraction:.01,autoSubmitTimeLimitMillis:6048E5},b=c.autoSubmitTimeLimitMillis,d=Date.now();return a.b&&b&&d-a.b<b?!1:Math.random()<c.fraction};vx.prototype.Ea=function(){return"mirror.cast.LogUtils"};vx.prototype.kb=function(){return[void 0,{lastAutoSubmitMillis:this.b}]};vx.prototype.jb=function(){var a=am(this);this.b=a&&a.lastAutoSubmitMillis||0};var wx=null;hb("mr.mirror.cast.LogUtils");var yx={Qx:"OFFER",Ot:"ANSWER",ty:"PRESENTATION",Dv:"GET_STATUS",Fz:"STATUS_RESPONSE",Cv:"GET_CAPABILITIES",mu:"CAPABILITIES_RESPONSE",fz:"RPC"};var xca=function(){this.capabilities=this.status=this.b=this.error=this.rpc=this.result=this.type=this.f=this.sessionId=null},zca=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var c;zx(JSON.parse(a),function(d){c=yca(d)},function(){throw Error("non-Object result from JSON parse");});return c}catch(d){var b=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(b+". Input was "+a);},yca=function(a){var c=new xca;null!=a.sessionId&&(c.sessionId=String(a.sessionId));Ax(a.seqNum,function(f){c.f=f},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var b=String(a.type).toUpperCase(),d=l(Object.keys(yx)),e=d.next();!e.done;e=d.next())if(yx[e.value]==b){c.type=b;break}if(!c.type)throw Error('not a known message "type"');
}"result"in a&&(c.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');c.rpc=new Uint8Array([].concat(n(atob(a.rpc))).map(function(f){return f.charCodeAt(0)}))}zx(a.error,function(f){c.error=Aca(f)},function(){throw Error('"error" must be an Object');});zx(a.answer,function(f){c.b=Bca(f)},function(){throw Error('"answer" must be an Object');});zx(a.status,function(f){c.status=Cca(f)},function(){throw Error('"status" must be an Object');
});zx(a.capabilities,function(f){c.capabilities=Dca(f)},function(){throw Error('"capabilities" must be an Object');});return c},zx=function(a,c,b){void 0!==a&&(a instanceof Object?c(a):b())},Ax=function(a,c,b){void 0!==a&&("number"!==typeof a?b():c(a))},Bx=function(a,c,b){void 0!==a&&(a instanceof Array&&a.every(function(d){return"number"===typeof d})?c(a):b())},Cx=function(a,c,b){void 0!==a&&(a instanceof Array?c(a.map(function(d){return String(d)})):b())},Eca=function(){this.j=null;this.b=[];this.f=
[];this.g=this.h=this.w=null},Bca=function(a){var c=new Eca;Ax(a.udpPort,function(b){c.j=b},function(){throw Error('"answer.udpPort" must be a number');});Bx(a.sendIndexes,function(b){c.b=b},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});Bx(a.ssrcs,function(b){c.f=b},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(c.w=String(a.IV));"receiverGetStatus"in a&&(c.h="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(c.g=
String(a.castMode));return c},Fca=function(){this.details=this.description=this.code=null},Aca=function(a){var c=new Fca;Ax(a.code,function(b){c.code=b},function(){throw Error('"error.code" must be a number');});"description"in a&&(c.description=String(a.description));zx(a.details,function(b){c.details=b},function(){throw Error('"error.details" must be an Object');});return c},Gca=function(){this.f=this.b=null},Cca=function(a){var c=new Gca;Ax(a.wifiSnr,function(b){c.b=b},function(){throw Error('"status.wifiSnr" must be a number');
});Bx(a.wifiSpeed,function(b){c.f=b},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return c},Hca=function(){this.f=this.b=null},Dca=function(a){var c=new Hca;Cx(a.mediaCaps,function(b){c.b=b},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');c.f=a.map(function(b){var d;zx(b,function(e){d=Ica(e)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return d})}return c},Jca=function(){this.g=this.l=this.w=this.j=this.s=this.b=this.o=this.f=this.initDataTypes=this.h=null},Ica=function(a){var c=new Jca;"keySystemName"in a&&(c.h=String(a.keySystemName));Cx(a.initDataTypes,function(b){c.initDataTypes=b},function(){throw Error('"capabilities.initDataTypes" must be an array');});Cx(a.codecs,function(b){c.f=b},function(){throw Error('"capabilities.codecs" must be an array');});Cx(a.secureCodecs,function(b){c.o=b},function(){throw Error('"capabilities.secureCodecs" must be an array');
});Cx(a.audioRobustness,function(b){c.b=b},function(){throw Error('"capabilities.audioRobustness" must be an array');});Cx(a.videoRobustness,function(b){c.s=b},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(c.j=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(c.w=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(c.l=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(c.g=String(a.distinctiveIdentifierSupport));return c};var Dx=function(a){this.m=hb("mr.mirror.cast.MessageDispatcher");this.h=a;this.b=null;this.f=new Map;this.g=0};Dx.prototype.subscribe=function(a,c){if(this.f.has(a))throw Error("Attempt to multiple-subscribe to the same response type: "+a);this.f.set(a,c);this.g=0;ob(this.m,"Added subscriber for "+a+"-type messages.");this.b||(this.b=Iw(this.h),this.b.onMessage=this.j.bind(this))};
var Ex=function(a,c){a.f.delete(c)&&ob(a.m,function(){return"Removed subscriber of "+c+"-type messages."});0==a.f.size&&a.b&&(a.b.ab(),a.b=null)};Dx.prototype.sendMessage=function(a){return this.b?"RPC"==a.type?this.b.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.b.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var Fx=function(a,c,b,d,e){var f=null,g=function(){Ex(a,b);null!=f&&(clearTimeout(f),f=null)};try{a.subscribe(b,function(k){e(k)&&g()})}catch(k){e(null,k);return}f=setTimeout(function(){g();e(null,Error("timeout"))},d);a.sendMessage(c).catch(function(k){g();e(null,k)})};
Dx.prototype.j=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var c=void 0;try{c=zca(a.data)}catch(d){c=d.message;break}if(c.type){var b=this.f.get(c.type);if(b)try{b(c);return}catch(d){c="Error thrown during delivery. Response was: "+(JSON.stringify(c)+". Error from subscriber callback ")+("was: "+d.message+".")}else c="Message was ignored: "+JSON.stringify(c)}else c="Message did not include response type: "+JSON.stringify(c)}while(0);
10>this.g?this.m.G(c):ob(this.m,c);++this.g}};var Gx=function(){this.b=Promise.resolve(1)},Ix=function(a,c,b){return Hx(a,function(d){return d==c},b)},Kca=function(a,c){var b=[3,4];return Hx(a,function(d){return-1!=b.indexOf(d)},c)},Jx=function(a,c){a.b=a.b.catch(function(){return 1});return Hx(a,function(){return!0},c)},Hx=function(a,c,b){var d,e,f=new Promise(function(g,k){d=g;e=k});a.b=a.b.then(function(g){if(!c(g))return e(Error("Operation requires a different starting checkpoint than "+g)),Promise.resolve(g);var k=new Lca(g);try{var m=b(k)}catch(p){m=
Promise.reject(p)}return m.then(function(p){return d(p)},function(p){return e(p)}).then(function(){if(null===k.b)throw Error("A prior operation that started at "+(g+" did not complete."));return k.b})},function(g){e(g);throw g;});return f},Lca=function(a){this.f=a;this.b=null},Kx=function(a,c){a.b="number"===typeof c?c:a.f};var Lx=chrome.cast.streaming,Nx=function(a,c,b,d,e){this.J=a.sessionId;this.s=a.eg;this.O=a.me;this.g=c;this.H=b;this.L=d;this.T=Mx(e,"onAnswer",this.s);this.V=Mx(e,"onSessionStop",this.s);this.m=hb("mr.mirror.cast.StreamingLaunchWorkflow");this.D=new Gx;this.l=this.C=this.o=this.f=this.b=this.w=this.j=this.h=null};
Nx.prototype.start=function(a,c,b){var d=this;if(!a&&!c)return Promise.reject(Error("No tracks to stream"));var e=a instanceof Ox,f=c instanceof Ox;(e&&c&&!f||f&&a&&!e)&&Hb("Mixing remoting and non-remoting tracks");return Ix(this.D,1,function(g){d.h=a;d.j=c;d.w=b;d.m.info(function(){return"Launching streaming for "+Px(d)+" "+("to a "+d.O+".")});return Mca(d).then(d.F.bind(d)).then(function(k){return Nca(d,k).then(function(m){d.T();var p=Oca(d,m,k);d.b=Qx(d,d.b,p);d.f=Qx(d,d.f,p);if(!d.b&&!d.f)throw Error("Receiver did not select any offers from: "+
JSON.stringify(k));d.C=!!m.h;d.l=function(v,A){v==d.b?d.w.hf("Audio stream (id="+v+") error: "+A):v==d.f&&d.w.hf("Video stream (id="+v+") error: "+A)};Lx.rtpStream.onError.addListener(d.l);return Pca(d,m,p)})}).then(function(){d.m.info(function(){return"Launched streaming for "+Px(d)});d.w.Ag(d);Kx(g,2);return{Pp:d.b,yt:d.f}})})};
Nx.prototype.stop=function(){var a=this;return Jx(this.D,function(c){if(!a.h&&!a.j)return Kx(c,1),Promise.resolve();a.m.info(function(){return"Stopping streaming for "+Px(a)+"."});a.l&&(Lx.rtpStream.onError.removeListener(a.l),a.l=null);if(a.w){var b=a.w.jh();a.w=null}else b=Promise.resolve();return b.then(function(){a.b&&(Lx.rtpStream.stop(a.b),Lx.rtpStream.destroy(a.b),a.b=null);a.f&&(Lx.rtpStream.stop(a.f),Lx.rtpStream.destroy(a.f),a.f=null);a.o&&(Lx.udpTransport.destroy(a.o),a.o=null);a.V();a.m.info(function(){return"Stopped streaming for "+
Px(a)+"."});a.h=null;a.j=null;Kx(c,1)})})};
var Qca=function(a,c){var b=JSON.stringify(c);return Promise.all([a.b&&new Promise(function(d){return Lx.rtpStream.getRawEvents(a.b,b,d)}),a.f&&new Promise(function(d){return Lx.rtpStream.getRawEvents(a.f,b,d)})]).catch(function(d){a.m.error("Unexpected error when calling getRawEvents()",d);return[]}).then(function(d){return new Blob(d.filter(function(e){return!!e}),{type:"application/gzip"})})},Rca=function(a){return Promise.all([a.b&&new Promise(function(c){return Lx.rtpStream.getStats(a.b,c)}),
a.f&&new Promise(function(c){return Lx.rtpStream.getStats(a.f,c)})]).catch(function(c){a.m.error("Unexpected error when calling getStats()",c);return[]}).then(function(c){return Object.assign.apply(Object,[{}].concat(n(c.filter(function(b){return!!b}))))})},Px=function(a){if(a.h&&a.j)var c="audio+video ";else if(a.h)c="audio-only ";else if(a.j)c="video-only ";else return"stopped";return a.h instanceof Ox||a.j instanceof Ox?c+"remoting":c+"streaming"},Mca=function(a){return new Promise(function(c){var b=
function(d,e,f){d&&!a.h&&(Lx.rtpStream.destroy(d),d=null);e&&!a.j&&(Lx.rtpStream.destroy(e),e=null);a.m.info(function(){return"Created Cast Streaming session: audioStreamId="+d+", videoStreamId="+e+"."});a.b=d;a.f=e;a.o=f;c()};a.h instanceof Ox||a.j instanceof Ox?Lx.session.create(null,null,b):Lx.session.create(a.h,a.j,b)})};
Nx.prototype.F=function(){for(var a=Mj(),c=Mj(),b=[],d=l([this.b,this.f]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.b,g=f?127:96,k=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,m=f?48E3:9E4,p=l(Lx.rtpStream.getSupportedParams(e)),v=p.next();!v.done;v=p.next())v=v.value,v.payload.payloadType=g,v.payload.maxLatency=this.g.maxLatencyMillis,v.payload.minLatency=this.g.minLatencyMillis,v.payload.animatedLatency=this.g.animatedLatencyMillis,v.payload.ssrc=
k,v.payload.clockRate=m,v.payload.aesKey=a,v.payload.aesIvMask=c,f?(v.payload.channels=2,v.payload.maxBitrate=this.g.audioBitrate,v.payload.maxFrameRate=100):(v.payload.minBitrate=this.g.minVideoBitrate,v.payload.maxBitrate=this.g.maxVideoBitrate,v.payload.maxFrameRate=this.g.maxFrameRate),b.push(new Sca(e,v));return b};
var Qx=function(a,c,b){c&&!b.some(function(d){return d.hg==c})&&(a.m.G("Destroying RTP stream not selected by the receiver: id="+c),Lx.rtpStream.destroy(c),c=null);return c},Nca=function(a,c){return new Promise(function(b,d){for(var e=[],f=0;f<c.length;++f){var g=c[f].params,k={index:f,codecName:g.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:g.payload.payloadType,ssrc:g.payload.ssrc,targetDelay:g.payload.animatedLatency,aesKey:g.payload.aesKey,aesIvMask:g.payload.aesIvMask,timeBase:"1/"+
g.payload.clockRate,receiverRtcpEventLog:a.g.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.g.dscpEnabled&&(k.receiverRtcpDscp=46);127==g.payload.payloadType?Object.assign(k,{type:"audio_source",bitRate:0<g.payload.maxBitrate?1E3*g.payload.maxBitrate:60*g.payload.maxFrameRate+g.payload.clockRate*g.payload.channels,sampleRate:g.payload.clockRate,channels:g.payload.channels}):Object.assign(k,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*g.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*g.payload.maxBitrate,resolutions:[{width:a.g.maxWidth,height:a.g.maxHeight}]});e.push(k)}var m=a.h instanceof Ox||a.j instanceof Ox?"remoting":"mirroring",p={type:"OFFER",sessionId:a.J,seqNum:rn(a.H),offer:{castMode:m,receiverGetStatus:!0,supportedStreams:e}};a.m.info(function(){return"Sending OFFER message: "+JSON.stringify(p)});Fx(a.L,p,"ANSWER",1E4,function(v,A){if(null==v)d(A);else if("ok"==v.result&&v.b){if(v.f!=p.seqNum)return a.m.G("Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(v)),!1;((A=v.b.g)&&A!=m||!A&&"mirroring"!=m)&&a.m.error("Expected receiver to ANSWER with castMode="+m+", but got: "+A);ob(a.m,function(){return"Received ANSWER: "+JSON.stringify(v)});b(v.b)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(v)));return!0})})},Oca=function(a,c,b){if(c.b.length!=c.f.length)return a.m.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(c)),[];for(var d=[],e={},f=0;f<c.b.length;e={rf:e.rf},++f){var g=c.b[f];if(0>g||g>=b.length)return a.m.error("Receiver selected invalid index ("+
g+" < "+b.length+") in ANSWER: "+JSON.stringify(c)),[];e.rf=b[g];if(d.some(function(k){return function(m){return m.hg==k.rf.hg}}(e)))return a.m.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(c)),[];e.rf.params.payload.feedbackSsrc=c.f[g];if(d.some(function(k){return function(m){return m.params.payload.feedbackSsrc==k.rf.params.payload.feedbackSsrc}}(e)))return a.m.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+JSON.stringify(c)),[];d.push(e.rf)}return d},
Pca=function(a,c,b){var d=null,e=function(){d&&(Lx.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(f,g){var k=c.j||2344;a.m.info(function(){return"Starting RTP streams to receiver at "+(a.s+":"+k)+(" for selected offers: "+JSON.stringify(b))});var m=a.o||-1;a.g.dscpEnabled&&(a.m.info("Enabled DSCP in sender."),Lx.udpTransport.setOptions(m,{DSCP:!0}));Lx.udpTransport.setDestination(m,{address:a.s,port:k});var p=new Set(b.map(function(A){return A.hg}));d=function(A){p.delete(A);
0==p.size&&f()};Lx.rtpStream.onStarted.addListener(d);m=l(b);for(var v=m.next();!v.done;v=m.next())v=v.value,Lx.rtpStream.toggleLogging(v.hg,a.g.enableLogging),Lx.rtpStream.start(v.hg,v.params);setTimeout(function(){g(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(f){e();throw f;})},Mx=function(a,c,b){var d=this;return a&&c in a?function(){try{a[c](b)}catch(e){d.m.error("Error from testHooks."+c,e)}}:function(){}},Sca=function(a,c){this.hg=a;this.params=c},Ox=function(){};var Rx=function(a,c,b,d,e,f){this.l=a;this.L=Tca(c,this.l.pb);this.H=new Nx(this.l.pb,b,d,e,f);this.C=e;this.j=new Gx;this.g=new Uca;this.D=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.m=hb("mr.mirror.cast.MediaRemoter");this.s=this.b=this.w=this.h=this.F=null;this.f=!0;this.o=this.J.bind(this)};
Rx.prototype.initialize=function(a,c){var b=this;return Ix(this.j,1,function(d){b.F=a;b.h=c;var e=b.D.createInterfacePtrAndBind();b.D.setConnectionErrorHandler(function(){b.m.info("Remoter mojo pipe connection error.");Sx(b)});b.b=new mojo.MirrorServiceRemotingSourcePtr;var f=ej(b.l.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+b.l.mediaSource);b.m.info("Connecting remoter to browser: tabId="+f);(Ni.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,
mojo.makeRequest(b.b));b.b.ptr.setConnectionErrorHandler(function(){b.m.info("RemotingSource mojo pipe connection error.");Sx(b)});return Vca(b).then(function(){if(b.f)b.b.onSinkAvailable(b.L);Kx(d,2)})})};
var Sx=function(a){return Jx(a.j,function(c){a.b&&(a.b.ptr.reset(),a.b=null);var b=a.w;a.w=null;a.h=null;a.F=null;a.D.close();chrome.settingsPrivate.onPrefsChanged.hasListener(a.o)&&chrome.settingsPrivate.onPrefsChanged.removeListener(a.o);return new Promise(function(d){window.setTimeout(function(){Tx(a).then(function(){Kx(c,1);d();b&&b()})},250)})})};h=Rx.prototype;h.Qs=function(a){Ux(this.g,a)};h.Ag=function(a){this.h&&this.h.Ag(a)};h.jh=function(){return this.h?this.h.jh():Promise.resolve()};
h.hf=function(a,c){this.m.error("Error during streaming: "+a,c);if(this.b)this.b.onError();Sx(this)};
h.start=function(){var a=this,c=!1;this.m.info(function(){c=!0;return"Starting next media remoting session."});c&&Wca(this.g,function(b){return a.m.info(b)});Xca(this.g);Ix(this.j,2,function(b){return(0,a.F)().then(function(d){a.w=d;a.C.subscribe("RPC",function(e){if(e.rpc){var f=a.g;e=e.rpc;f.w&&(++f.l,f.f+=e.length,f.w(e))}});Kx(b,3)}).catch(function(d){return Tx(a).then(function(){Kx(b);throw d;})})}).then(function(){a.m.info("Remoting started successfully.")}).catch(function(b){a.m.error("Failed to start remoting",
b);a.b.onError()})};h.ot=function(a,c){var b=this;return Ix(this.j,3,function(d){return b.H.start(a?new Ox:null,c?new Ox:null,b).then(function(e){Yca(b.g,function(f){return b.C.sendMessage(f)},function(f){b.b.onMessageFromSink(f)});Kx(d,4);return{audio_stream_id:e.Pp||-1,video_stream_id:e.yt||-1}}).catch(function(e){return Tx(b).then(function(){Kx(d);throw e;})})}).catch(function(d){b.m.error("Failed to start remoting streams",d);Sx(b);return{audio_stream_id:-1,video_stream_id:-1}})};
h.stop=function(a){var c=this;Kca(this.j,function(b){c.b.onStopped(a);return Tx(c).then(function(){c.m.info("Remoting stopped.");Kx(b,5);(0,c.w)().then(function(){return Ix(c.j,5,function(d){if(c.b&&c.f)c.b.onSinkAvailable(c.L);Kx(d,2);return Promise.resolve()})}).catch(function(d){throw d;});c.w=null})}).catch(function(b){c.m.error("Failed to stop remoting: ",b);Sx(c)})};
h.nq=function(){null===this.s&&(this.s=of(this.l.pb.eg).then(function(a){return a.f||!1}));return this.s.then(function(a){return{rate:(a?1E7:5E6)/8}})};
var Tx=function(a){return a.H.stop().then(function(){Ex(a.C,"RPC");Zca(a.g);Vx(a.g)})},Vca=function(a){return new Promise(function(c){chrome.settingsPrivate.getPref("media_router.media_remoting.enabled",function(b){chrome.runtime.lastError?a.m.error("Encountered error getting media remoting pref: "+JSON.stringify(chrome.runtime.lastError)):b.type!=chrome.settingsPrivate.PrefType.BOOLEAN?a.m.error("Pref value not a boolean: "+JSON.stringify(b)):(a.f=!!b.value,a.m.info("Initializing mediaRemotingEnabled_ with value read from pref: "+
a.f));chrome.settingsPrivate.onPrefsChanged.hasListener(a.o)||chrome.settingsPrivate.onPrefsChanged.addListener(a.o);c()})})};
Rx.prototype.J=function(a){if(this.b){a=l(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,"media_router.media_remoting.enabled"==c.key){if(c.type!=chrome.settingsPrivate.PrefType.BOOLEAN){this.m.error("Pref value not a boolean: "+JSON.stringify(c));break}a=!!c.value;if(this.f==a)break;this.f=a;this.m.info("mediaRemotingEnabled_ changed to: "+this.f);if(this.f)this.b.onSinkAvailable(this.L);else this.b.onStopped(mojo.RemotingStopReason.USER_DISABLED);break}}};
var Tca=function(a,c){var b=this,d=new mojo.RemotingSinkMetadata;d.features=[];d.friendly_name=c.kt||"";d.audio_capabilities=[];d.video_capabilities=[];var e=mojo.RemotingSinkAudioCapability,f=mojo.RemotingSinkVideoCapability,g=d.audio_capabilities,k=d.video_capabilities,m=c.me||"";(a.b||[]).forEach(function(p){switch(p){case "audio":g.push(e.CODEC_BASELINE_SET);break;case "aac":g.push(e.CODEC_AAC);break;case "opus":g.push(e.CODEC_OPUS);break;case "video":k.push(f.CODEC_BASELINE_SET);break;case "4k":k.push(f.SUPPORT_4K);
break;case "h264":k.push(f.CODEC_H264);break;case "vp8":k.push(f.CODEC_VP8);break;case "vp9":m.startsWith("Chromecast Ultra")&&k.push(f.CODEC_VP9);break;case "hevc":m.startsWith("Chromecast Ultra")&&k.push(f.CODEC_HEVC);break;default:b.m.info("Unknown mediaCap name: "+p)}});c.me&&"Chromecast Ultra"==c.me&&k.push(f.SUPPORT_4K);return d};Rx.prototype.estimateTransmissionCapacity=Rx.prototype.nq;Rx.prototype.stop=Rx.prototype.stop;Rx.prototype.startDataStreams=Rx.prototype.ot;Rx.prototype.start=Rx.prototype.start;
Rx.prototype.sendMessageToSink=Rx.prototype.Qs;
var Uca=function(){this.w=this.j=this.b=null;this.s=this.f=this.l=this.g=this.o=0;this.h=null},Xca=function(a){a.b=[];Wx(a,performance.now())},Yca=function(a,c,b){a.j=c;a.w=b;a.b?(c=a.b,a.b=null,c.forEach(function(d){return Ux(a,d.data).then(d.Ss,d.nn)})):Wx(a,performance.now())},Zca=function(a){if(a.b){var c=Error("Stop before delivering pending message");a.b.forEach(function(b){return b.nn(c)});a.b=null}a.j=null;a.w=null},Ux=function(a,c){if(a.j){var b=btoa(String.fromCharCode.apply(null,c));++a.o;
a.g+=c.length;return a.j({type:"RPC",rpc:b})}return a.b?new Promise(function(d,e){a.b.push({data:c,Ss:d,nn:e})}):Promise.reject(Error("RPC pipe not started"))},Wca=function(a,c){Vx(a);a.h=setInterval(function(){if(a.b)var b=a.b.length+" messages are waiting to send.";else{b=performance.now();var d=(b-a.s)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.o+" messages ("+Math.round(a.g/d)+" bytes/sec) and ")+("received "+a.l+" messages ("+Math.round(a.f/d)+" ")+"bytes/sec).";Wx(a,b);b=d}c(b)},
3E4)},Vx=function(a){null!=a.h&&(clearInterval(a.h),a.h=null)},Wx=function(a,c){a.o=0;a.g=0;a.l=0;a.f=0;a.s=c};var $ca=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},ada=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var Xx=function(a,c,b,d,e){this.g=new Nx(a,c,b,d,void 0===e?null:e);this.m=hb("mr.mirror.cast.MediaStreamer");this.j=new Gx;this.h=this.f=this.b=this.w=null};Xx.prototype.start=function(a,c){var b=this;return Ix(this.j,1,function(d){b.w=a;b.b=$ca(a);b.b&&"ended"==b.b.readyState&&(b.b=null);b.f=ada(a);b.f&&"ended"==b.f.readyState&&(b.f=null);if(!b.b&&!b.f)return Kx(d),Promise.reject(Error("No MediaStream tracks to stream."));b.h=c;return b.g.start(b.b,b.f,b.h).then(function(){return Kx(d,2)})})};
Xx.prototype.stop=function(){var a=this;return Jx(this.j,function(c){return a.g.stop().then(function(){a.b=null;a.f=null;a.w=null;a.h=null;Kx(c,1)})})};var bda=function(a){return Ix(a.j,2,function(c){a.m.info("Suspending media streaming...");return a.g.stop().then(function(){a.m.info("Suspended media streaming.");Kx(c,3)})})};
Xx.prototype.resume=function(){var a=this;return Ix(this.j,3,function(c){a.b&&"ended"==a.b.readyState&&(a.b=null);a.f&&"ended"==a.f.readyState&&(a.f=null);if(!a.b&&!a.f)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.m.info("Resuming media streaming...");return a.g.start(a.b,a.f,a.h).then(function(){a.m.info("Resumed media streaming.");Kx(c,2)})})};var Yx=function(a,c,b){this.j=a;this.h=c;this.g=b;this.m=hb("mr.mirror.cast.WifiStatusMonitor");this.b=null;this.f=[]};Yx.prototype.start=function(){var a=this;null==this.b&&(ob(this.m,"Starting Wifi Status Monitoring."),this.f=[],this.g.subscribe("STATUS_RESPONSE",function(c){return cda(a,c)}),this.b=setInterval(function(){return Zx(a)},12E4),Zx(this))};Yx.prototype.stop=function(){null!=this.b&&(ob(this.m,"Stopping Wifi Status Monitoring."),clearInterval(this.b),this.b=null,Ex(this.g,"STATUS_RESPONSE"))};
var cda=function(a,c){if(null!=a.b)if(c.status){var b={};null!=c.status.b&&(b.wifiSnr=c.status.b);null!=c.status.f&&(b.wifiSpeed=c.status.f[3]);0==Object.keys(b).length?a.m.G(function(){return"No status fields populated in response: "+JSON.stringify(c)}):(b.timestamp=Date.now(),30==a.f.length&&a.f.shift(),a.f.push(b),a.m.info(function(){return"Current Wifi status: "+JSON.stringify(b)}))}else a.m.G(function(){return"Ignoring response without status: "+JSON.stringify(c)})},Zx=function(a){a.g.sendMessage({type:"GET_STATUS",
sessionId:a.j,seqNum:rn(a.h),get_status:["wifiSnr","wifiSpeed"]})};var $x=function(a,c,b,d){this.L=c.eg;this.l={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:tj(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:c.me};this.F=b;this.C=d;this.h=this.f=this.o=this.w=this.j=this.s=this.g=null;this.b=[]};$x.prototype.Ag=function(a){null!=this.f&&clearInterval(this.f);this.g=a;this.s=Date.now();this.f=setInterval(this.D.bind(this,a),9E5)};
$x.prototype.jh=function(){null!=this.f&&(clearInterval(this.f),this.f=null);if(null!=this.g){var a=this.D(this.g);this.g=null;return a}return Promise.resolve()};$x.prototype.hf=function(a,c){null==this.j&&(this.j=Date.now(),"function"===typeof a?this.w=a():"string"===typeof a&&(this.w=a),c&&"string"===typeof c.stack&&(this.o=c.stack))};
var dda=function(a,c){return(null==a.g?Promise.resolve():a.D(a.g)).then(function(){var b=c.map(function(d){d=ay(a,d);var e=d.map(function(g){return g.events}).filter(function(g){return null!=g}),f=["["];d.map(function(g){return g.gg}).forEach(function(g,k){0<k&&f.push(",");f.push(g)});f.push("]");return{events:new Blob(e,{type:"application/gzip"}),gg:new Blob(f,{type:"application/json"})}});a.b=[];return b})};
$x.prototype.D=function(a){var c=this;if(null!=this.h)return this.h;var b=of(this.L).then(function(d){d={receiverVersion:d.b,receiverConnected:d.h,receiverOnEthernet:d.f,receiverHasUpdatePending:d.g,receiverUptimeSeconds:d.j};Object.assign(d,c.l);var e=Date.now();Object.assign(d,{startTime:c.s,endTime:e,activity:Px(a),receiverWifiStatus:Array.from(c.C.f)});c.s=e;null!=c.j&&(Object.assign(d,{streamingErrorTime:c.j,streamingErrorMessage:c.w,streamingErrorCause:c.o}),c.j=null,c.w=null,c.o=null);return d});
return(this.h=Promise.all([b.then(function(d){return Qca(a,d)}),b,Rca(a)]).then(function(d){var e=l(d);d=e.next().value;var f=e.next().value;e=e.next().value;c.b.push({events:d,gg:new Blob([JSON.stringify(Object.assign({tags:f},e))],{type:"application/json"})});c.b=ay(c,c.F);c.h=null}))||Promise.resolve()};
var ay=function(a,c){c-=2;for(var b=[],d=a.b.length-1;0<=d;--d){c-=a.b[d].gg.size+1;if(0>c)break;b.push({events:null,gg:a.b[d].gg});if(null!=a.b[d].events){var e=a.b[d].events.size;c>=e&&(b[b.length-1].events=a.b[d].events,c-=e)}}return b.reverse()};var by=hb("mr.NetworkUtils"),cy=function(a,c){return xi?new Promise(function(b,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,c,function(e){chrome.runtime.lastError?(by.G("Unable to set TDLS state: state = "+c+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+c+".")):(by.info("TDLS state changed: state = "+c+", status = "+e),b(e))})}):Promise.reject("TDLS feature not enabled.")};var dy=function(a,c,b,d){d=void 0===d?null:d;qj.call(this,c);var e=c.pb;this.D=e.sessionId;this.J=e.eg;this.L=a;this.O=d;this.m=hb("mr.mirror.cast.Session");this.s=new Gx;this.o=new qn("mirror.cast.SeqNumGenerator");this.l=new Dx(c.id);this.w=new Xx(e,this.L,this.o,this.l,this.O);this.h=null;this.b=new $x(a,e,b,new Yx(this.D,this.o,this.l));this.g=!1;this.C=null};q(dy,qj);h=dy.prototype;
h.start=function(a){var c=this;return Ix(this.s,1,function(b){var d=px();return eda(c).then(function(e){c.g=e;return c.w.start(a,c)}).then(function(){if(c.w.g.C){var e=c.b;e.l.tdlsIsOn=c.g;e.C.start();fda(c)}else c.b.l.tdlsIsOn=c.g;d.end();c.C=qx();Kx(b,2);return c})})};
h.stop=function(){var a=this;return Jx(this.s,function(c){a.C&&(a.C.end(),a.C=null);a.b.C.stop();return a.w.stop().then(function(){return a.h?Sx(a.h):Promise.resolve()}).then(function(){a.h=null;return a.g?gda(a):Promise.resolve()}).then(function(){a.g=!1;Kx(c,4)})})};
h.ln=function(){var a=this,c={sessionId:this.D,seqNum:rn(this.o),type:"PRESENTATION",icons:[],title:oj(this.vc)};this.m.info("Sending session metadata update to receiver: "+this.D);this.l.sendMessage(c).catch(function(b){a.m.G("Failed to send activity to sink: "+b.message)})};h.Ag=function(a){this.b.Ag(a)};h.jh=function(){return this.b.jh()};h.hf=function(a,c){this.b.hf(a,c);this.m.error(a,c);this.stop()};
var ey=function(a,c){return dda(a.b,c)},eda=function(a){return a.L.useTdls?cy(a.J,!0).then(function(c){if("Connected"==c)return a.m.info("Successfully enabled TDLS."),!0;a.m.G("Did not enable TDLS: result="+c);return!1}).catch(function(c){a.m.G("Error while calling enableTDLS()",c);return!1}):Promise.resolve(!1)},gda=function(a){return cy(a.J,!1).catch(function(c){return a.m.error("Error while turning TDLS back off",c)})},fda=function(a){hda(a).then(function(c){(c.b||[]).includes("video")?ida(a,c):
a.m.G(function(){return"Receiver incapable of Media Remoting: "+JSON.stringify(c)})}).catch(function(c){a.m.G("None/Invalid capabilites response. Media Remoting disabled.",c)})},hda=function(a){return new Promise(function(c,b){var d={type:"GET_CAPABILITIES",sessionId:a.D,seqNum:rn(a.o)};a.m.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});Fx(a.l,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return b(f),!0;if("ok"!=e.result||!e.capabilities)return b(Error("Bad response: "+
JSON.stringify(e))),!0;if(e.f!=d.seqNum)return a.m.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+JSON.stringify(e)}),!1;ob(a.m,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});c(e.capabilities);return!0})})},ida=function(a,c){Ix(a.s,2,function(b){var d=a.f.pb.me||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return a.m.G("HACK: Media Remoting disabled because the receiver model--"+('"'+d+'" according to discovery--is not a Chromecast.')),
Kx(b),Promise.resolve();a.h=new Rx(a.f,c,a.L,a.o,a.l,a.O);return a.h.initialize(a.T.bind(a),a).catch(function(e){a.m.error("Media Remoting start failed: "+e.message,e)}).then(function(){return Kx(b)})})};dy.prototype.T=function(){var a=this;return Ix(this.s,2,function(c){return new Promise(function(b,d){bda(a.w).then(function(){Kx(c,3);a.F=!0;hj(a);b(a.V.bind(a))}).catch(function(e){a.hf("Failed to suspend MediaStreamer before starting remoting",e);d(e)})})})};
dy.prototype.V=function(){var a=this;return Ix(this.s,3,function(c){return new Promise(function(b,d){a.w.resume().then(function(){Kx(c,2);a.F=!1;hj(a);b()}).catch(function(e){a.hf("Failed resume MediaStreamer after ending remoting mode",e);d(e)})})})};var fy=function(){fj.call(this,"cast_streaming");this.w=this.s=this.L=this.F=this.h=null;this.Va=this.H="";this.Z=this.o=!1;this.fa=this.qa.bind(this);this.J=this.O=this.T=this.V=this.j=null};q(fy,fj);h=fy.prototype;h.Cg=function(a){this.o=a||!1;this.Z=!0};h.getName=function(){return"cast_streaming"};
h.Hj=function(a,c,b,d,e){var f=this;if(!this.o)return fj.prototype.Hj.call(this,a,c,b,d,e);this.R.info("Start mirroring on route "+a.id);if(!this.Z)return qi(Error("Not initialized"));var g=new Promise(function(k,m){f.l().then(function(){if(aj(c)&&b.shouldCaptureVideo)return Ki().then(function(p){f.Va=p})}).then(function(){return e?e(a).b:a}).then(function(p){f.H=c;jda(f,p);var v=f.F.createInterfacePtrAndBind(),A=f.L.createInterfacePtrAndBind(),G=kda(p,b);lda(f,p,c,d);if(!f.h)throw new ui("Error to get mirroring service host");
f.s=new mojo.MirroringCastMessageChannelPtr;f.V=px();f.h.start(G,v,A,mojo.makeRequest(f.s));f.j=new qj(a,f.g.Si.bind(f.g));hj(f.j);mda(f,p,c);f.O=function(){return k(p)};f.J=m}).catch(function(p){f.R.info("Mirroring launch error: "+p);f.bh(p.reason);m(p)})});return ri(g)};h.xh=function(a,c){return new dy(a,c,20969472,null)};h.eh=function(){rx(0)};h.Zg=function(){rx(1)};h.Xh=function(){rx(2)};h.ah=function(){Bb("MediaRouter.CastStreaming.Session.End")};
h.bh=function(a){Cb("MediaRouter.CastStreaming.Start.Failure",a,ti)};h.dh=function(){Bb("MediaRouter.CastStreaming.Stream.End")};
h.ui=function(a){var c=this;return this.o?Promise.resolve():(new Promise(function(b){return chrome.metricsPrivate.getIsCrashReportingEnabled(b)})).then(function(b){var d=b&&wca(),e=[9351424];d&&e.push(20969472);return ey(a,e).then(function(f){var g=f[f.length-1];f=lm(f[0].events).catch(function(k){c.R.error("Failed to persist events Blob.",k)});d&&0<g.events.size?ux(g.events,void 0,c.ur.bind(c)):b&&tx("stats.json",g.gg,void 0,void 0);return f})})};h.ur=function(a){a&&(xx().b=Date.now())};
h.Gj=function(a){if(this.o)return eb();this.R.info("Received message to upload logs for "+a);return this.b?ey(this.b,[20969472]).then(function(c){c=l(c).next().value;return 0==c.events.size?"":ux(c.events,a)}):Promise.resolve(nda(this,a))};
var nda=function(a,c){var b=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==b||1>b.length)b=null;else{for(var d=new Uint16Array(b.length),e=0;e<b.length;++e)d[e]=b.charCodeAt(e);b=d.buffer;d=(new Uint8Array(b,b.byteLength-1,1))[0];b=new Uint8Array(b,0,b.byteLength-(0==d?2:1));b=new Blob([b],{type:"application/gzip"})}if(null!=b&&0!=b.size)return lm(new Blob),a.R.info("Uploading saved logs for feedback."),ux(b,c)};h=fy.prototype;
h.onError=function(a){this.J&&(this.J(a),this.O=this.J=null);this.R.info("Mirroring service error: "+a);this.l()};h.didStart=function(){this.O&&(this.O(),this.O=this.J=null);this.V&&(this.V.end(),this.V=null);this.T=qx();$i(this.H)?this.eh():aj(this.H)?this.Zg():cj(this.H)&&this.Xh()};h.didStop=function(){this.l()};h.send=function(a){if(this.w){var c=JSON.parse(a.jsonFormatData);ob(this.R,function(){return"Sending message: "+JSON.stringify(c)});this.w.sendMessage(a.jsonFormatData,{namespace:a.messageNamespace})}};
h.vr=function(a){if(a&&(a.namespace_===mojo.MirroringWebRtcNamespace||a.namespace_===mojo.MirroringRemotingNamespace)&&this.s){var c=new mojo.MirroringCastMessage;c.messageNamespace=a.namespace_;"string"!==typeof a.data?this.R.info("Received non-string as JSON"):(c.jsonFormatData=a.data,this.s.send(c))}};
var jda=function(a,c){a.F=new mojo.Binding(mojo.MirroringSessionObserver,a,null);a.L=new mojo.Binding(mojo.MirroringCastMessageChannel,a,null);a.w=Iw(c.id);a.w.onMessage=a.vr.bind(a)},kda=function(a,c){var b=new mojo.MirroringSessionParameters;b.receiverAddress=new mojo.IPAddress;b.receiverAddress.addressBytes=a.pb.eg.split(".").map(function(d){return parseInt(d,10)});b.receiverModelName=a.pb.me;b.type=c.shouldCaptureVideo&&c.shouldCaptureAudio?mojo.MirroringSessionType.AUDIO_AND_VIDEO:c.shouldCaptureVideo?
mojo.MirroringSessionType.VIDEO_ONLY:mojo.MirroringSessionType.AUDIO_ONLY;return b},lda=function(a,c,b,d){a.h=new mojo.MirroringServiceHostPtr;c=c.pb.tabId||-1;$i(b)?a.g.getMirroringServiceHostForTab(c,mojo.makeRequest(a.h)):aj(b)?a.g.getMirroringServiceHostForDesktop(-1,a.Va,mojo.makeRequest(a.h)):cj(b)?(c=new mojo.Url,c.url=b,a.g.getMirroringServiceHostForOffscreenTab(c,d||"",mojo.makeRequest(a.h))):a.h=null},mda=function(a,c,b){$i(b)&&!chrome.tabs.onUpdated.hasListener(a.fa)&&chrome.tabs.onUpdated.addListener(a.fa);
($i(b)||cj(b))&&kj(a.j,c.pb.tabId)};fy.prototype.qa=function(a,c,b){Zi(14);this.j&&lj(this.j,a,c,b)};
fy.prototype.l=function(){chrome.tabs.onUpdated.removeListener(this.fa);return this.o?this.Z?this.h?(this.h.ptr.reset(),this.s=this.h=null,this.w&&this.w.ab(),this.w=null,this.F&&(this.F.close(),this.F=null),this.L&&(this.L.close(),this.L=null),this.g.Uh(this.j.f.id),this.j=null,this.Va=this.H="",this.T&&(this.T.end(),this.T=null),this.ah(),Promise.resolve(!0)):Promise.resolve(!1):Promise.reject("Not initialized"):fj.prototype.l.call(this)};
fy.prototype.Ij=function(a,c,b,d,e,f){return this.o?qi(Error("Mirroring service does not support updating stream")):fj.prototype.Ij.call(this,a,c,b,d,e,f)};fy.prototype.send=fy.prototype.send;fy.prototype.didStop=fy.prototype.didStop;fy.prototype.didStart=fy.prototype.didStart;fy.prototype.onError=fy.prototype.onError;var oda=new fy;Wi("mr.mirror.cast.Service",oda);
