'use strict'; 
var zon_config = {
"CONFIG_MAKEFLAGS": "DIST=APP RELEASE=y AUTO_SIGN=y CONFIG_BATREQ=y CONFIG_BAT_CYCLE=y CONFIG_BAT_PLATFORM=app_win64r",
"CONFIG_LUM": false,
"ARCH_CPU": "X86",
"BUILDTYPE_DEBUG": false,
"_RELEASE": true,
"_RELEASE_LEVEL": 2,
"CONFIG_BUILD_DATE": "06-Aug-19 14:31:02",
"ZON_VERSION": "1.147.262",
"ZON_VERSION_1": 1,
"ZON_VERSION_2": 147,
"ZON_VERSION_3": 262,
"ZON_COPYRIGHT_YEAR": "2019",
"SVC_EXE": "hola_svc.exe",
"SVC_EXE_ANDROID": "libhola_svc.so",
"UPDATER_EXE": "hola_updater.exe",
"NET_SVC_EXE": "net_svc.exe",
"NET_SVC_ZIP": "net_svc-x64-1.147.262.zip",
"NET_SVC_ZIP_PDB": "net_svc-x64-1.147.262-pdb.zip",
"SVC_AGENTS_POOL": "107.170.225.182:22224:zagent551,162.243.166.138:22224:zagent1106,45.55.90.210:22224:zagent1110,66.85.185.71:22224:zagent3,108.170.8.186:22224:zagent97",
"BEXT_CHROME_ID_REL": "pnknnijoleibcpmkdcooclmnjmmdhgbg",
"BEXT_CHROME_CWS_ID_REL": "gkojfkhlekighikafcpjkiklfbnlmeio",
"BEXT_OPERA_ADDONS_ID_REL": "ekmmelpnmfdegjhnmadddcfjcahpajnm",
"BEXT_FF_ID_REL_SIGNED": "ff_ext@hola.org",
"BEXT_FF_ORIGIN_SIGNED": "resource://ff_ext-at-hola-dot-org",
"BEXT_FF_ID_REL": "jid1-4P0kohSJxU1qGg@jetpack",
"BEXT_FF_ORIGIN": "resource://jid1-4p0kohsjxu1qgg-at-jetpack",
"CONFIG_MP_CHROME": false,
"CONFIG_MP_OPERA": true,
"BEXT": 1,
"BEXT_LUM_CHROME_WWW_ID": "bgnknkfnajhbeohlmmkopjlokfebbpac",
"BEXT_VA_CHROME_ID_REL": "chgpmaaockmdehmidghebcjafhihlgha",
"HOLA_ADBLOCK_ID_REL": "lalfpjdbhpmnhfofkckdpkljeilmogfl"
};
if (typeof module=='object'&&module&&module.exports)
    module.exports = zon_config;else if (typeof define=='function') define(zon_config);
